add rendering of number nodes
zwenza/ukejs pull request #5
Opened 2018-04-07 15:48 UTC by alexnavratil

- add rendering of number nodes
- provide example for working number node rendering

2018-04-09 17:35 UTC, zwenza requested changes

2018-04-09 17:35 UTC, zwenza commented on example/index.js
> +      age: 21
Please fix the indentation

2018-04-11 19:44 UTC, alexnavratil commented on example/index.js
> +      age: 21
fixed in https://github.com/zwenza/ukejs/pull/5/commits/511c157cbf2003c9ff19ca1a932d5e91fc617d4b

2018-04-11 20:59 UTC, zwenza commented
Thanks for the contribution !

2018-04-11 20:59 UTC, merged